# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mega Millionaires' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.8.1'
pod 'SwiftyJSON', '~> 4.0'
  # Pods for Mega Millionaires

  target 'Mega MillionairesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Mega MillionairesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
